In [15]:
print('''-------- PRABAL MANHAS EXP 9 HIRING ANALYIS MULTIPLE LINEAR REGRESSION -------------
CASE 1 - 2 yr experience, 9 test score, 6 interview score
CASE 2 - 12 yr experience, 10 test score, 10 interview score''')


-------- PRABAL MANHAS EXP 9 HIRING ANALYIS MULTIPLE LINEAR REGRESSION -------------
CASE 1 - 2 yr experience, 9 test score, 6 interview score
CASE 2 - 12 yr experience, 10 test score, 10 interview score


In [1]:
#IMPORTING ALL MODULES AND WORD2NUMBER INSTALLATION USING PIP TO CONVERT TEXT STRINGS VALUE TO INTEGER FORMAT AT LATER STAGE
pip install word2number
import pandas as pd
import numpy as np
from sklearn import linear_model
from word2number import w2n
import math

  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5582 sha256=6592db71a2fc923ccfa97c615d3930189ec74886354e3d5c2668e2b3913c910f
  Stored in directory: /root/.cache/pip/wheels/4b/c3/77/a5f48aeb0d3efb7cd5ad61cbd3da30bbf9ffc9662b07c9f879
Successfully built word2number


In [2]:
# READING THE UPLOADED HIRING DATASET FILE
df = pd.read_csv('hiring.csv')
# PRINTING THE CONTENTS OF FILE SUCH AS EXPERIENCE TEST CORE AND INTERVIEW SCORE
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [3]:
# AS SOME DISCREPENCIES ARE THERE, SO MAKE IT EASY FILLING ZERO AT NAN PLACES
df.experience = df.experience.fillna('zero')
# PRINTING THE UPDATED DATA SET 
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [4]:
# NOW CONVERTING THESE TEXT STRING NUMBERS TO INTEGER VALUES
df.experience = df.experience.apply(w2n.word_to_num)
# PRINTING THE NEW DATASET WITH INT AS THEIR VALUES
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [5]:
# NOW I AM FINDING THE MEAN OF ALL TEST SCORES OUT OF 10
mean_test_score = math.floor(df['test_score(out of 10)'].mean())
mean_test_score

7

In [6]:
# AND AT MISSING PLACES NAN FILLING IT WITH THE MEAN TEST SCORE
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(mean_test_score)
# PRINT UPDATED DATASET
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [7]:
# BUILDING A LINEAR REGRESSION MODEL NOW WITH EXPERIENCE, TEST SCORE, INTERVIEW SCORE AND SALARY
reg = linear_model.LinearRegression()
reg.fit(df[['experience', 'test_score(out of 10)', 'interview_score(out of 10)']], df['salary($)'])

LinearRegression()

In [8]:
# FINDING REGRESSION COEFFICIENTS
reg.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [9]:
# FINDING REGRESSION INTERCEPT
reg.intercept_

14992.651446693148

In [10]:
# NOW PERFORMING REGRESSION PREDICTION FOR CASE 1 - (EXPERIENCE = 2 YRS, TEST SCORE  - 9  AND INTERVIEW SCORE - 6)
reg.predict([[2, 9, 6]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([53713.86677124])

In [11]:
# PREDICTING THE SALARY
2922.26901502*2 + 2221.30909959*9 + 2147.48256637*6 + 14992.651446693118


53713.86677126312

In [12]:
# NOW PERFORMING REGRESSION PREDICTION FOR CASE 2 - (EXPERIENCE = 12 YRS, TEST SCORE  - 10  AND INTERVIEW SCORE - 10)

reg.predict([[12, 10, 10]])


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([93747.79628651])

In [13]:
2922.26901502*12 + 2221.30909959*10 + 2147.48256637*10 + 14992.651446693118


93747.79628653312

In [14]:
print('''THANKYOU
\t PRABAL MANHAS
\t\t 20BCS4513''')

THANKYOU
	 PRABAL MANHAS
		 20BCS4513
